[package]
name = "orderbook-v1"
version = "0.1.0"
authors = ["Logan Saether <x@logansaether.com>"]
edition = "2018"

[dependencies]
orml-traits = { default-features = false, version = '0.3' }
pallet-balances = { version = "2.0.1", default-features = false }
zeitgeist-primitives = { default-features = false, path = '../../primitives' }

[dependencies.codec]
default-features = false
features = ['derive']
package = 'parity-scale-codec'
version = '1.3.1'

[dependencies.frame-support]
default-features = false
version = '2.0.1'

[dependencies.frame-system]
default-features = false
version = '2.0.1'

[dependencies.sp-core]
default-features = false
version = '2.0.1'

[dependencies.sp-io]
default-features = false
version = '2.0.1'

[dependencies.sp-runtime]
default-features = false
version = '2.0.1'

[dependencies.sp-std]
default-features = false
version = '2.0.1'

[dev-dependencies]
orml-tokens = { default-features = false, version = '0.3' }

[dev-dependencies.sp-core]
default-features = false
version = '2.0.1'

[dev-dependencies.sp-io]
default-features = false
version = '2.0.1'

[dev-dependencies.sp-runtime]
default-features = false
version = '2.0.1'

[features]
default = ["std"]
std = [
    'codec/std',
    'frame-support/std',
    'frame-system/std',
    'orml-traits/std',
    'pallet-balances/std',
    'sp-core/std',
    'sp-io/std',
    'sp-std/std',
    'zeitgeist-primitives/std'
]
