name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Initializes
      run: |
        rustup install nightly-2020-10-06
        rustup target add wasm32-unknown-unknown --toolchain nightly-2020-10-06
        rustup component add rustfmt --toolchain nightly-2020-10-06-x86_64-unknown-linux-gnu
    - name: Rustfmt
      run: |
        cargo fmt --all -- --check
    - name: Builds WASM
      run: |
        make build-wasm
    - name: Checks
      run: |
        make check
    - name: Runs tests
      run: |
        cargo test
